version: "3.7"
services:
    web:
        build:
            context: .
            args:
                WORK_DIR: ${WORK_DIR}
        ports:
            - "${APP_PORT}:${APP_PORT}"
        volumes:
            - ./resources:${WORK_DIR}/resources:rw
        command: npm run start
